version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile

    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

  front:
    image: node:12-alpine
    volumes:
      - ./frontend:/app:cached
    depends_on:
      - back
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
    tty: true
