# Generated by Django 3.2.4 on 2021-06-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('time_limit', models.PositiveSmallIntegerField(verbose_name='Time')),
                ('finished_date', models.DateTimeField(blank=True, null=True, verbose_name='Finished Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
